name: PR Checks
on: [push, pull_request]

jobs:
  lint:
    name: Ensure the code is formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> $GITHUB_PATH

      - name: Check formatting
        run: dprint check

  test:
    name: Run Bun Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate definitions
        run: make ci-setup build

      - name: Test
        run: bun test

  check:
    name: Check Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate definitions
        run: make ci-setup build

      - name: Check Typescript for errors
        run: bun src/scripts/check.ts