name: Push Checks
on: [push]

jobs:
  docker:
    name: Verify that Docker can build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build the Dockerfile
        run: docker compose build
  openscad-node:
    name: Verify that OpenSCAD keycap scripts work (Node/Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm ci

      - name: Install openscad
        run: sudo apt-get update && sudo apt-get install -y openscad

      - name: Compile Code
        run: make ci-setup build

      - name: Build simple keycaps
        run: OPENSCAD=$(which openscad) make keycaps-simple
  openscad-bun:
    name: Verify that OpenSCAD keycap scripts work (Bun/Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install npm dependencies
        run: bun install # --frozen-lockfile

      - name: Install openscad
        run: sudo apt-get update && sudo apt-get install -y openscad

      - name: Compile Code
        run: make ci-setup build

      - name: Build simple keycaps
        run: OPENSCAD=$(which openscad) make keycaps-simple

  setup-linux-bun:
    name: Verify Set up (Bun/Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Quickstart
        run: make quickstart
        env:
          SKIP_VARIANTS: 1

  setup-windows-bun:
    name: Verify Set up (Bun/Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies
        run: bun install

      - name: Quickstart
        run: bun make quickstart
        env:
          SKIP_VARIANTS: 1

  setup-node-bun:
    name: Verify Set up (Node/Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm dependencies
        run: npm install

      - name: Quickstart
        run: npm run nodemake quickstart
        env:
          SKIP_VARIANTS: 1
